# Reload tmux config using prefix-r
unbind r
bind r source-file ~/.tmux.conf

# Rebind prefix
set -g prefix `

# Enable mouse support
set -g mouse on

# vim shortcuts for scrolling and copying
set-w -g mode-keys vi

# Update binding for copying to match vim
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# vim-like navigation around panes
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Use vim keybindings in copy mode
setw -g mode-keys vi

set -g renumber-windows on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
